In [1]:
#import libraries
import numpy as np

In [2]:
X = np.array(([2,9], [1,5], [3,6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
X = X/np.max(X,axis=0)  # maximum of X array longitudinally
y = y/100

In [3]:
print(y)

[[0.92]
 [0.86]
 [0.89]]


In [4]:
# Sigmoid function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [5]:
# Derivative of Sigmoid function
def derivatives_sigmoid(x):
    return x * (1 - x)

In [37]:
# Variable initialization
epoch = 200 # Setting training iterations
lr = 0.5 # Setting learning rate

In [38]:
inputlayer_neurons = 2 # number of features in data set
hiddenlayer_neurons = 3 # number of hidden layers neurons
output_neurons = 1
# weight and bias initialization

In [39]:
wh = np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh = np.random.uniform(size=(1,hiddenlayer_neurons))
wout = np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout = np.random.uniform(size=(1,output_neurons))

In [40]:
# draws a random range of numbers uniformly of dim x*y
for i in range(epoch):
    #Forward Propagation
    hinp1 = np.dot(X,wh)
    hinp = hinp1 + bh
    hlayer_act = sigmoid(hinp)
    outinp1 = np.dot(hlayer_act,wout)
    outinp = outinp1 + bout
    output = sigmoid(outinp)
    
    # Backpropagation
    EO = y - output
    outgrad = derivatives_sigmoid(output)
    d_output = EO * outgrad
    EH = d_output.dot(wout.T)
    hiddengrad = derivatives_sigmoid(hlayer_act) # how much hidden layer wts contributed to error
    
    d_hiddenlayer = EH * hiddengrad
    
    wout += hlayer_act.T.dot(d_output) *lr
    
    wh += X.T.dot(d_hiddenlayer) *lr
    
    print("-------------Iteration--", i+1,"Starts-------------")
    print("Input: \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n", output)
    print("-------------Iteration--", i+1,"Ends---------------\n")
    
print("Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n", output)

-------------Iteration-- 1 Starts-------------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.91035636]
 [0.89753075]
 [0.90968319]]
-------------Iteration-- 1 Ends---------------

-------------Iteration-- 2 Starts-------------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.91002173]
 [0.89719114]
 [0.90934595]]
-------------Iteration-- 2 Ends---------------

-------------Iteration-- 3 Starts-------------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.90969214]
 [0.89685676]
 [0.90901378]]
-------------Iteration-- 3 Ends---------------

-------------Iteration-- 4 Starts-------------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.