# Import Libraries

In [22]:
from numpy import array
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

# Load Data

In [10]:
data = loadtxt('pima-indians-diabetes.csv', delimiter=",")
data

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [13]:
X = data[:,0:8]
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [16]:
Y = data[:,8]
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

# Define the Keras Model

In [17]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu')) # 12 -- means the number of neurons
model.add(Dense(8, activation='relu')) # 8 -- means the number of neurons is 8
model.add(Dense(1, activation='sigmoid')) # 1 means the number of neurons is 1

2022-03-25 08:51:29.721500: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-03-25 08:51:29.722239: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-03-25 08:51:29.729207: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


# Compile the Model

In [18]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# Fit the Model

In [19]:
model.fit(X,Y, epochs=200, batch_size=10)

2022-03-25 09:06:52.334743: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-03-25 09:06:52.355027: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2099940000 Hz


Epoch 1/200
77/77 [==============================] - 1s 2ms/step - loss: 3.5290 - accuracy: 0.5824
Epoch 2/200
77/77 [==============================] - 0s 2ms/step - loss: 1.1663 - accuracy: 0.6148
Epoch 3/200
77/77 [==============================] - 0s 3ms/step - loss: 0.7695 - accuracy: 0.6486
Epoch 4/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6897 - accuracy: 0.6588
Epoch 5/200
77/77 [==============================] - 0s 3ms/step - loss: 0.6838 - accuracy: 0.6489
Epoch 6/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6651 - accuracy: 0.6621
Epoch 7/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6476 - accuracy: 0.6644
Epoch 8/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6222 - accuracy: 0.6631
Epoch 9/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6116 - accuracy: 0.6732
Epoch 10/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6197 - accuracy: 0.6921
Epoch 11/

77/77 [==============================] - 0s 2ms/step - loss: 0.4989 - accuracy: 0.7581
Epoch 84/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4949 - accuracy: 0.7644
Epoch 85/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4722 - accuracy: 0.7717
Epoch 86/200
77/77 [==============================] - 0s 1ms/step - loss: 0.5097 - accuracy: 0.7697
Epoch 87/200
77/77 [==============================] - 0s 1ms/step - loss: 0.5009 - accuracy: 0.7552
Epoch 88/200
77/77 [==============================] - 0s 1ms/step - loss: 0.5049 - accuracy: 0.7613
Epoch 89/200
77/77 [==============================] - 0s 1ms/step - loss: 0.5156 - accuracy: 0.7415
Epoch 90/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5223 - accuracy: 0.7443
Epoch 91/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4969 - accuracy: 0.7623
Epoch 92/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5265 - accuracy: 0.7488
Epoch 93/200


77/77 [==============================] - 0s 2ms/step - loss: 0.4635 - accuracy: 0.7896
Epoch 165/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4936 - accuracy: 0.7666
Epoch 166/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4527 - accuracy: 0.7817
Epoch 167/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4889 - accuracy: 0.7729
Epoch 168/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4583 - accuracy: 0.7753
Epoch 169/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4548 - accuracy: 0.7836
Epoch 170/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4610 - accuracy: 0.7830
Epoch 171/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4596 - accuracy: 0.7911
Epoch 172/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4672 - accuracy: 0.7809
Epoch 173/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4511 - accuracy: 0.7671
Epoc

# Evaluate the Model

In [21]:
_,accuracy = model.evaluate(X,Y)
print('Accuracy: %.2f'%(accuracy*100))

24/24 [==============================] - 0s 4ms/step - loss: 0.4429 - accuracy: 0.8034
Accuracy: 80.34


# Predict the Model

In [24]:
Xp = array([[6.0, 158.0, 72.0, 35.0, 0.0, 55.5, 0.627, 50.0]])
Yp = model.predict(Xp)

In [30]:
print(Xp[0])

[  6.    158.     72.     35.      0.     55.5     0.627  50.   ]


In [33]:
print(Yp[0])

[0.95639265]
