In [29]:
import numpy as np
import pandas as pd
import scipy
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import Binarizer
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

In [21]:
data = pd.read_csv('diabetes.csv')
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [8]:
array = data.values
array

array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [9]:
X = array[:,0:8]
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [10]:
Y = array[:,8]
Y

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1.,
       1., 0., 0., 0., 0.

# Rescale Data

In [27]:
scaler = MinMaxScaler(feature_range=(0,1))
rescaledX = scaler.fit_transform(X)

np.set_printoptions(precision=3)
print(rescaledX[0:5,:])

# Creating Model

In [30]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

2022-04-08 09:33:50.342014: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-04-08 09:33:50.343623: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-08 09:33:50.362446: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.


In [33]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [34]:
model.fit(X,Y, epochs=200, batch_size=10)

2022-04-08 09:35:24.762854: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2022-04-08 09:35:24.787464: I tensorflow/core/platform/profile_utils/cpu_utils.cc:112] CPU Frequency: 2099940000 Hz


Epoch 1/200
77/77 [==============================] - 1s 2ms/step - loss: 5.4047 - accuracy: 0.6030
Epoch 2/200
77/77 [==============================] - 0s 2ms/step - loss: 3.3274 - accuracy: 0.6038
Epoch 3/200
77/77 [==============================] - 0s 2ms/step - loss: 2.6175 - accuracy: 0.5641
Epoch 4/200
77/77 [==============================] - 0s 2ms/step - loss: 1.8949 - accuracy: 0.6291
Epoch 5/200
77/77 [==============================] - 0s 2ms/step - loss: 1.5394 - accuracy: 0.6174
Epoch 6/200
77/77 [==============================] - 0s 2ms/step - loss: 1.6033 - accuracy: 0.5880
Epoch 7/200
77/77 [==============================] - 0s 1ms/step - loss: 1.2588 - accuracy: 0.6478
Epoch 8/200
77/77 [==============================] - 0s 2ms/step - loss: 1.5097 - accuracy: 0.6147: 0s - loss: 1.4124 - accuracy: 0.
Epoch 9/200
77/77 [==============================] - 0s 2ms/step - loss: 1.2367 - accuracy: 0.6402
Epoch 10/200
77/77 [==============================] - 0s 2ms/step - loss: 1

77/77 [==============================] - 0s 2ms/step - loss: 0.5393 - accuracy: 0.7551
Epoch 164/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5302 - accuracy: 0.7502
Epoch 165/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5125 - accuracy: 0.7474
Epoch 166/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5147 - accuracy: 0.7427
Epoch 167/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5304 - accuracy: 0.7568
Epoch 168/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5107 - accuracy: 0.7482
Epoch 169/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5500 - accuracy: 0.7108
Epoch 170/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5069 - accuracy: 0.7513
Epoch 171/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5343 - accuracy: 0.7616
Epoch 172/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4631 - accuracy: 0.7898
Epoc

In [35]:
_,accuracy = model.evaluate(X,Y)
print('Accuracy: %.2f'%(accuracy*100))

24/24 [==============================] - 0s 3ms/step - loss: 0.5992 - accuracy: 0.7044
Accuracy: 70.44


# Strandradize data

In [36]:
scaler = StandardScaler().fit(X)
rescaledX = scaler.transform(X)

In [37]:
np.set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


# Creating Model

In [38]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [40]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [41]:
model.fit(X,Y, epochs=200, batch_size=10)

Epoch 1/200
77/77 [==============================] - 1s 3ms/step - loss: 20.1622 - accuracy: 0.3436
Epoch 2/200
77/77 [==============================] - 0s 2ms/step - loss: 2.0673 - accuracy: 0.4593
Epoch 3/200
77/77 [==============================] - 0s 2ms/step - loss: 0.8091 - accuracy: 0.6026
Epoch 4/200
77/77 [==============================] - 0s 2ms/step - loss: 0.7451 - accuracy: 0.6495
Epoch 5/200
77/77 [==============================] - 0s 2ms/step - loss: 0.7350 - accuracy: 0.6576
Epoch 6/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6927 - accuracy: 0.6422
Epoch 7/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6890 - accuracy: 0.6524
Epoch 8/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6715 - accuracy: 0.6603
Epoch 9/200
77/77 [==============================] - 0s 1ms/step - loss: 0.6710 - accuracy: 0.6494
Epoch 10/200
77/77 [==============================] - 0s 1ms/step - loss: 0.6729 - accuracy: 0.6604
Epoch 11

77/77 [==============================] - 0s 2ms/step - loss: 0.6611 - accuracy: 0.6274
Epoch 84/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6418 - accuracy: 0.6586
Epoch 85/200
77/77 [==============================] - 0s 1ms/step - loss: 0.6554 - accuracy: 0.6375
Epoch 86/200
77/77 [==============================] - 0s 1ms/step - loss: 0.6548 - accuracy: 0.6370
Epoch 87/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6399 - accuracy: 0.6612
Epoch 88/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6401 - accuracy: 0.6578
Epoch 89/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6549 - accuracy: 0.6360
Epoch 90/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6565 - accuracy: 0.6337
Epoch 91/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6333 - accuracy: 0.6720
Epoch 92/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6580 - accuracy: 0.6324
Epoch 93/200


In [42]:
_,accuracy = model.evaluate(X,Y)
print('Accuracy: %.2f'%(accuracy*100))

24/24 [==============================] - 0s 2ms/step - loss: 0.6462 - accuracy: 0.6510
Accuracy: 65.10


# Normalize Data

In [43]:
scaler = Normalizer().fit(X)
normalizedX = scaler.transform(X)

In [44]:
np.set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[ 0.64   0.848  0.15   0.907 -0.693  0.204  0.468  1.426]
 [-0.845 -1.123 -0.161  0.531 -0.693 -0.684 -0.365 -0.191]
 [ 1.234  1.944 -0.264 -1.288 -0.693 -1.103  0.604 -0.106]
 [-0.845 -0.998 -0.161  0.155  0.123 -0.494 -0.921 -1.042]
 [-1.142  0.504 -1.505  0.907  0.766  1.41   5.485 -0.02 ]]


# Creating Model

In [45]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [46]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [47]:
model.fit(X,Y, epochs=200, batch_size=10)

Epoch 1/200
77/77 [==============================] - 1s 2ms/step - loss: 2.4338 - accuracy: 0.4841
Epoch 2/200
77/77 [==============================] - 0s 2ms/step - loss: 1.1077 - accuracy: 0.5669
Epoch 3/200
77/77 [==============================] - 0s 2ms/step - loss: 0.9376 - accuracy: 0.6327
Epoch 4/200
77/77 [==============================] - 0s 2ms/step - loss: 0.8894 - accuracy: 0.5798
Epoch 5/200
77/77 [==============================] - 0s 2ms/step - loss: 0.7849 - accuracy: 0.6123
Epoch 6/200
77/77 [==============================] - 0s 2ms/step - loss: 0.7777 - accuracy: 0.6106
Epoch 7/200
77/77 [==============================] - 0s 1ms/step - loss: 0.7911 - accuracy: 0.6093
Epoch 8/200
77/77 [==============================] - 0s 1ms/step - loss: 0.7578 - accuracy: 0.6420
Epoch 9/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6854 - accuracy: 0.6350
Epoch 10/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6824 - accuracy: 0.6334
Epoch 11/

77/77 [==============================] - 0s 2ms/step - loss: 0.5561 - accuracy: 0.7085
Epoch 84/200
77/77 [==============================] - 0s 1ms/step - loss: 0.5583 - accuracy: 0.7116
Epoch 85/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5524 - accuracy: 0.6985
Epoch 86/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5526 - accuracy: 0.7008
Epoch 87/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5863 - accuracy: 0.6935
Epoch 88/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5633 - accuracy: 0.7118
Epoch 89/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5652 - accuracy: 0.6930
Epoch 90/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5793 - accuracy: 0.6915
Epoch 91/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5443 - accuracy: 0.7120
Epoch 92/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5634 - accuracy: 0.7091
Epoch 93/200


In [48]:
_,accuracy = model.evaluate(X,Y)
print('Accuracy: %.2f'%(accuracy*100))

24/24 [==============================] - 0s 3ms/step - loss: 0.4864 - accuracy: 0.7305
Accuracy: 73.05


# Binarize Data

In [49]:
binarizer = Binarizer(threshold=0.0).fit(X)
binaryX = binarizer.transform(X)

In [50]:
np.set_printoptions(precision=3)
print(binaryX[0:5,:])

[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]


# Creating Model

In [51]:
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [52]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [53]:
model.fit(X,Y, epochs=200, batch_size=10)

Epoch 1/200
77/77 [==============================] - 1s 2ms/step - loss: 10.2635 - accuracy: 0.6390
Epoch 2/200
77/77 [==============================] - 0s 2ms/step - loss: 2.2076 - accuracy: 0.5538
Epoch 3/200
77/77 [==============================] - 0s 2ms/step - loss: 1.2873 - accuracy: 0.5016
Epoch 4/200
77/77 [==============================] - 0s 2ms/step - loss: 0.9601 - accuracy: 0.5291
Epoch 5/200
77/77 [==============================] - 0s 2ms/step - loss: 0.7755 - accuracy: 0.5694
Epoch 6/200
77/77 [==============================] - 0s 1ms/step - loss: 0.7490 - accuracy: 0.5431
Epoch 7/200
77/77 [==============================] - 0s 2ms/step - loss: 0.7030 - accuracy: 0.6177
Epoch 8/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6429 - accuracy: 0.6349
Epoch 9/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6833 - accuracy: 0.6259
Epoch 10/200
77/77 [==============================] - 0s 2ms/step - loss: 0.6677 - accuracy: 0.6325
Epoch 11

77/77 [==============================] - 0s 2ms/step - loss: 0.5091 - accuracy: 0.7582
Epoch 164/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4867 - accuracy: 0.7674
Epoch 165/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4769 - accuracy: 0.7704
Epoch 166/200
77/77 [==============================] - 0s 1ms/step - loss: 0.4955 - accuracy: 0.7612
Epoch 167/200
77/77 [==============================] - 0s 1ms/step - loss: 0.4911 - accuracy: 0.7473
Epoch 168/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4742 - accuracy: 0.7836
Epoch 169/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4991 - accuracy: 0.7428
Epoch 170/200
77/77 [==============================] - 0s 2ms/step - loss: 0.5248 - accuracy: 0.7606
Epoch 171/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4718 - accuracy: 0.7673
Epoch 172/200
77/77 [==============================] - 0s 2ms/step - loss: 0.4734 - accuracy: 0.7783
Epoc

In [55]:
_,accuracy = model.evaluate(X,Y)
print('Accuracy: %.2f'%(accuracy*100))

24/24 [==============================] - 0s 3ms/step - loss: 0.4590 - accuracy: 0.7812
Accuracy: 78.12
