# Aim

To implement Gray-Level Co-Occurrence Matrix

# Algorithm

    Import greycomatrix from the skimage feature module in Python
    Import numpy library as np
    To create a numerical multi-dimensional array called as image
    Call a function called result with the help of greycomatrix
    Print the result

# Code

Import libraries

In [1]:
from skimage.feature import greycomatrix
import numpy as np

In [8]:
image = np.array([[0,0,1,1],[0,0,1,1],[0,2,2,2,],[2,2,3,3]],dtype = np.uint8)
image

array([[0, 0, 1, 1],
       [0, 0, 1, 1],
       [0, 2, 2, 2],
       [2, 2, 3, 3]], dtype=uint8)

In [9]:
result = greycomatrix(image,[1],[0,np.pi/4,np.pi/2,3*np.pi/4], levels=4,symmetric=True,normed=True)

C:\Users\rosha\anaconda3\lib\site-packages\skimage\feature\__init__.py:35: skimage_deprecation: Function ``greycomatrix`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycomatrix`` instead.
  removed_version='1.0')


In [10]:
print(result)

[[[[0.16666667 0.11111111 0.25       0.22222222]]

  [[0.08333333 0.05555556 0.         0.05555556]]

  [[0.04166667 0.16666667 0.08333333 0.        ]]

  [[0.         0.         0.         0.        ]]]


 [[[0.08333333 0.05555556 0.         0.05555556]]

  [[0.16666667 0.11111111 0.16666667 0.11111111]]

  [[0.         0.05555556 0.08333333 0.11111111]]

  [[0.         0.         0.         0.        ]]]


 [[[0.04166667 0.16666667 0.08333333 0.        ]]

  [[0.         0.05555556 0.08333333 0.11111111]]

  [[0.25       0.         0.08333333 0.22222222]]

  [[0.04166667 0.11111111 0.08333333 0.05555556]]]


 [[[0.         0.         0.         0.        ]]

  [[0.         0.         0.         0.        ]]

  [[0.04166667 0.11111111 0.08333333 0.05555556]]

  [[0.08333333 0.         0.         0.        ]]]]
