# Single Layer Perceptron For NOT, AND, OR , NAND, NOR

In [14]:
import numpy as np

def unit_step(v):
    if v >= 0:
        return 1;
    else:
        return 0;
    
def perceptron(x,w,b):
    v = np.dot(x,w) + b
    y = unit_step(v)
    
    return y

def NOT(x):
    w = -1
    b = 0.5
    return perceptron(x,w,b)

print("NOT({}) = {}".format(0,NOT(0)));
print("NOT({}) = {}".format(1,NOT(1)));
print("\n\n")

def AND(x):
    w = np.array([1,1])
    b = -1.5
    return perceptron(x,w,b)

print("AND({},{}) = {}".format(0,0,AND([0,0])))
print("AND({},{}) = {}".format(0,1,AND([0,1])))
print("AND({},{}) = {}".format(1,0,AND([1,0])))
print("AND({},{}) = {}".format(1,1,AND([1,1])))
print("\n\n")

def NAND(x):
    a = AND(x)
    n = NOT(a)
    return n

print("NAND({},{}) = {}".format(0,0,NAND([0,0])))
print("NAND({},{}) = {}".format(0,1,NAND([0,1])))
print("NAND({},{}) = {}".format(1,0,NAND([1,0])))
print("NAND({},{}) = {}".format(1,1,NAND([1,1])))
print("\n\n")


def OR(x):
    w = np.array([1,1])
    b = -0.5
    return perceptron(x,w,b)

print("OR({},{}) = {}".format(0,0,OR([0,0])))
print("OR({},{}) = {}".format(0,1,OR([0,1])))
print("OR({},{}) = {}".format(1,0,OR([1,0])))
print("OR({},{}) = {}".format(1,1,OR([1,1])))
print("\n\n")

def NOR(x):
    o = OR(x)
    n = NOT(o)
    return n


print("NOR({},{}) = {}".format(0,0,NOR([0,0])))
print("NOR({},{}) = {}".format(0,1,NOR([0,1])))
print("NOR({},{}) = {}".format(1,0,NOR([1,0])))
print("NOR({},{}) = {}".format(1,1,NOR([1,1])))
print("\n\n")
   

NOT(0) = 1
NOT(1) = 0



AND(0,0) = 0
AND(0,1) = 0
AND(1,0) = 0
AND(1,1) = 1



NAND(0,0) = 1
NAND(0,1) = 1
NAND(1,0) = 1
NAND(1,1) = 0



OR(0,0) = 0
OR(0,1) = 1
OR(1,0) = 1
OR(1,1) = 1



NOR(0,0) = 1
NOR(0,1) = 0
NOR(1,0) = 0
NOR(1,1) = 0





# Single Layer Perceptron For Linear Regression

In [103]:
w = [0,0]  # weights

threshold = 0

bias = 1

learning_rate = 0.001

max_iterations = 1000

x = [
    [0.72,0.82,-1],
    [0.92,-0.4,-1],
    [0.78,0.86,-1],
    [0.34,0.11,1],
    [0.12,-0.23,1],
    [-0.1,-0.9,1]
]


y = 0 # output

answer = ""  # correct or error

for k in range(1,max_iterations):
    hits = 0
    
    for i in range(0,len(x)):
        sum = 0
        
        # weigthed sum
        for j in range(0,len(x[i])-1):
            sum += x[i][j]*w[j]
            
        output  = sum + bias
        
        if output > threshold:
            y = 1
        else:
            y = -1
            
        # update weights if the output does not match
        if y == x[i][2]:
            hits += 1
        else:
            for j in range(0,len(w)):
                w[j] += learning_rate*x[i][2]*x[i][j]
            bias += learning_rate*x[i][2]
                
        answer = "Error - Updating weight to: "+ str(w)
        
        
        # print answer
        if y == 1:
            print("\n"+answer)
        elif y == -1:
            print("\n"+answer)
            
    if hits == len(x):
        print("\n--------------------------------------------------------------------")
        print("functionality learned with "+str(k)+" iterations!")
        break;


Error - Updating weight to: [-0.0007199999999999999, -0.00082]

Error - Updating weight to: [-0.00164, -0.00041999999999999996]

Error - Updating weight to: [-0.0024200000000000003, -0.0012799999999999999]

Error - Updating weight to: [-0.0024200000000000003, -0.0012799999999999999]

Error - Updating weight to: [-0.0024200000000000003, -0.0012799999999999999]

Error - Updating weight to: [-0.0024200000000000003, -0.0012799999999999999]

Error - Updating weight to: [-0.0031400000000000004, -0.0021]

Error - Updating weight to: [-0.00406, -0.0017]

Error - Updating weight to: [-0.0048400000000000006, -0.0025599999999999998]

Error - Updating weight to: [-0.0048400000000000006, -0.0025599999999999998]

Error - Updating weight to: [-0.0048400000000000006, -0.0025599999999999998]

Error - Updating weight to: [-0.0048400000000000006, -0.0025599999999999998]

Error - Updating weight to: [-0.005560000000000001, -0.0033799999999999998]

Error - Updating weight to: [-0.0064800000000000005, -0.0


Error - Updating weight to: [-0.46745999999999754, -0.19755999999999774]

Error - Updating weight to: [-0.4683799999999975, -0.19715999999999773]

Error - Updating weight to: [-0.4683799999999975, -0.19715999999999773]

Error - Updating weight to: [-0.4683799999999975, -0.19715999999999773]

Error - Updating weight to: [-0.4683799999999975, -0.19715999999999773]

Error - Updating weight to: [-0.4683799999999975, -0.19715999999999773]

Error - Updating weight to: [-0.4683799999999975, -0.19715999999999773]

Error - Updating weight to: [-0.4692999999999975, -0.19675999999999771]

Error - Updating weight to: [-0.4692999999999975, -0.19675999999999771]

Error - Updating weight to: [-0.4692999999999975, -0.19675999999999771]

Error - Updating weight to: [-0.4692999999999975, -0.19675999999999771]

Error - Updating weight to: [-0.4692999999999975, -0.19675999999999771]

Error - Updating weight to: [-0.4692999999999975, -0.19675999999999771]

Error - Updating weight to: [-0.4702199999999975,

In [ ]:
np.random.random()

# Single Layer Perceptron For Classification

In [104]:
import sys
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
import numpy as np

x = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([[0], [1], [1], [0]])

model=Sequential()
model.add(Dense(2,input_shape=(2,),activation='sigmoid'))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='mse',optimizer='sgd',metrics=['accuracy'])

model.fit(x,y,epochs=100,batch_size=10)

_,accuracy = model.evaluate(x,y)

print('Accuracy: %.2f'%(accuracy*100))

Epoch 1/100
1/1 [==============================] - 1s 726ms/step - loss: 0.2573 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 7ms/step - loss: 0.2573 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2573 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 0.2572 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 0.2572 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 4ms/step - loss: 0.2572 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2572 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 0.2571 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2571 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 5ms/step - loss: 0.2571 - accuracy: 0.5000
Epoch 11/100
1/1 [=========

# Linear Regression using Multilayer Perceptron

In [113]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np
from keras import Sequential
from sklearn.model_selection import train_test_split
from keras.layers import Dense

data = load_iris()

df = pd.DataFrame(data.data,columns = data.feature_names)
df["species"] = data.target
df

df.isnull().sum() # checking if null values present or not

df.describe()

df.corr()

x = df.iloc[:,:4]
x

y = df.iloc[:,4:]
y

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=1)

model = Sequential()
model.add(Dense(36,input_dim=4,activation='relu'))
model.add(Dense(18,activation='relu'))
model.add(Dense(9,activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(1,activation='linear'))

model.compile(optimizer='adam',loss='mse',metrics=['accuracy'])

history = model.fit(x_train,y_train,epochs=200,validation_split=0.2)

_,accuracy = model.evaluate(x_test,y_test)
print('\n\n')
print('Accuracy: %.2f'%(accuracy*100))


Epoch 1/200
3/3 [==============================] - 1s 193ms/step - loss: 0.7578 - accuracy: 0.2708 - val_loss: 0.5542 - val_accuracy: 0.4583
Epoch 2/200
3/3 [==============================] - 0s 23ms/step - loss: 0.6701 - accuracy: 0.2708 - val_loss: 0.5270 - val_accuracy: 0.4583
Epoch 3/200
3/3 [==============================] - 0s 20ms/step - loss: 0.6050 - accuracy: 0.2708 - val_loss: 0.4769 - val_accuracy: 0.4583
Epoch 4/200
3/3 [==============================] - 0s 22ms/step - loss: 0.5359 - accuracy: 0.2708 - val_loss: 0.4331 - val_accuracy: 0.4583
Epoch 5/200
3/3 [==============================] - 0s 22ms/step - loss: 0.4886 - accuracy: 0.2708 - val_loss: 0.3875 - val_accuracy: 0.4583
Epoch 6/200
3/3 [==============================] - 0s 25ms/step - loss: 0.4447 - accuracy: 0.2708 - val_loss: 0.3507 - val_accuracy: 0.4583
Epoch 7/200
3/3 [==============================] - 0s 23ms/step - loss: 0.4013 - accuracy: 0.2708 - val_loss: 0.3193 - val_accuracy: 0.4583
Epoch 8/200
3/3 [==

3/3 [==============================] - 0s 22ms/step - loss: 0.0357 - accuracy: 0.6042 - val_loss: 0.0622 - val_accuracy: 0.7500
Epoch 118/200
3/3 [==============================] - 0s 23ms/step - loss: 0.0340 - accuracy: 0.6042 - val_loss: 0.0604 - val_accuracy: 0.7500
Epoch 119/200
3/3 [==============================] - 0s 24ms/step - loss: 0.0342 - accuracy: 0.6042 - val_loss: 0.0608 - val_accuracy: 0.7500
Epoch 120/200
3/3 [==============================] - 0s 23ms/step - loss: 0.0338 - accuracy: 0.6042 - val_loss: 0.0615 - val_accuracy: 0.7500
Epoch 121/200
3/3 [==============================] - 0s 22ms/step - loss: 0.0344 - accuracy: 0.6042 - val_loss: 0.0627 - val_accuracy: 0.7500
Epoch 122/200
3/3 [==============================] - 0s 23ms/step - loss: 0.0340 - accuracy: 0.6042 - val_loss: 0.0606 - val_accuracy: 0.7500
Epoch 123/200
3/3 [==============================] - 0s 23ms/step - loss: 0.0344 - accuracy: 0.6042 - val_loss: 0.0606 - val_accuracy: 0.7500
Epoch 124/200
3/3 [=

Epoch 175/200
3/3 [==============================] - 0s 19ms/step - loss: 0.0321 - accuracy: 0.6042 - val_loss: 0.0644 - val_accuracy: 0.7500
Epoch 176/200
3/3 [==============================] - 0s 21ms/step - loss: 0.0321 - accuracy: 0.6042 - val_loss: 0.0624 - val_accuracy: 0.7500
Epoch 177/200
3/3 [==============================] - 0s 23ms/step - loss: 0.0315 - accuracy: 0.6042 - val_loss: 0.0619 - val_accuracy: 0.7500
Epoch 178/200
3/3 [==============================] - 0s 22ms/step - loss: 0.0330 - accuracy: 0.6042 - val_loss: 0.0633 - val_accuracy: 0.7500
Epoch 179/200
3/3 [==============================] - 0s 23ms/step - loss: 0.0316 - accuracy: 0.6042 - val_loss: 0.0613 - val_accuracy: 0.7500
Epoch 180/200
3/3 [==============================] - 0s 24ms/step - loss: 0.0327 - accuracy: 0.6042 - val_loss: 0.0618 - val_accuracy: 0.7500
Epoch 181/200
3/3 [==============================] - 0s 19ms/step - loss: 0.0327 - accuracy: 0.6042 - val_loss: 0.0680 - val_accuracy: 0.7500
Epoch 

# Naive Baye's

In [147]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix

data = load_iris()
df = pd.DataFrame(data.data,columns=data.feature_names)
df['species'] = data.target
df

x = df.iloc[:,:4]
x

y = df.iloc[:,4:]
y

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.20,random_state=82)

sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

nvclassifier = GaussianNB()
nvclassifier.fit(x_train,y_train)

y_pred = nvclassifier.predict(x_test)
y_pred

cm = confusion_matrix(y_test,y_pred)
print(cm)

a = cm.shape
corrpred = 0
falsepred = 0

for row in range(a[0]):
    for c in range(a[1]):
        if row == c:
            corrpred += cm[row,c]
        else:
            falsepred += cm[row,c]
            
print('\nCorrect Predictions: ',corrpred)
print('\nFalse Predictions: ',falsepred)
print('\nAccuracy: %.2f' %(corrpred/(cm.sum())*100))


[[39  0  0]
 [ 0 39  0]
 [ 0 11 31]]

Correct Predictions:  109

False Predictions:  11

Accuracy: 90.83


C:\Users\rosha\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Principal Component Analysis

In [164]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig


A = array([[1,2],[3,4],[5,6],[7,8],[9,10]])
print(A)

M = mean(A.T,axis=1)
print()
print(M)

C = A - M
print()
print(C)

V = cov(C.T)
print()
print(V)

values,vectors = eig(V)
print()
print(vectors)
print(values)


P = vectors.T.dot(C.T)
print()
print(P.T)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

[5. 6.]

[[-4. -4.]
 [-2. -2.]
 [ 0.  0.]
 [ 2.  2.]
 [ 4.  4.]]

[[10. 10.]
 [10. 10.]]

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
[2.00000000e+01 2.22044605e-15]

[[-5.65685425e+00 -4.44089210e-16]
 [-2.82842712e+00 -2.22044605e-16]
 [ 0.00000000e+00  0.00000000e+00]
 [ 2.82842712e+00  2.22044605e-16]
 [ 5.65685425e+00  4.44089210e-16]]


# Gray Level Co-occurence Matrix

In [171]:
from skimage.feature import greycomatrix
import numpy as np

image = np.array([[0,0,1,1],[0,0,1,1],[0,2,2,2],[2,2,3,3]])
image

result = greycomatrix(image,[1],[0,np.pi/4,np.pi/2,3*np.pi/4],levels=4,symmetric=True,normed=True)
print(result)

[[[[0.16666667 0.11111111 0.25       0.22222222]]

  [[0.08333333 0.05555556 0.         0.05555556]]

  [[0.04166667 0.16666667 0.08333333 0.        ]]

  [[0.         0.         0.         0.        ]]]


 [[[0.08333333 0.05555556 0.         0.05555556]]

  [[0.16666667 0.11111111 0.16666667 0.11111111]]

  [[0.         0.05555556 0.08333333 0.11111111]]

  [[0.         0.         0.         0.        ]]]


 [[[0.04166667 0.16666667 0.08333333 0.        ]]

  [[0.         0.05555556 0.08333333 0.11111111]]

  [[0.25       0.         0.08333333 0.22222222]]

  [[0.04166667 0.11111111 0.08333333 0.05555556]]]


 [[[0.         0.         0.         0.        ]]

  [[0.         0.         0.         0.        ]]

  [[0.04166667 0.11111111 0.08333333 0.05555556]]

  [[0.08333333 0.         0.         0.        ]]]]


C:\Users\rosha\anaconda3\lib\site-packages\skimage\feature\__init__.py:35: skimage_deprecation: Function ``greycomatrix`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycomatrix`` instead.
  removed_version='1.0')


# Clustering Algorithm

In [179]:
from sklearn.cluster import KMeans
import numpy as np

x = np.array([[1,2],[1,4],[1,0],[10,2],[10,4],[10,0]])
x

kmeans = KMeans(n_clusters=2,random_state=1).fit(x)
print(kmeans.labels_)
print()
print(kmeans.predict([[12,3]]))
print()
print(kmeans.predict([[2,4]]))
print()
print(kmeans.cluster_centers_)

[0 0 0 1 1 1]

[1]

[0]

[[ 1.  2.]
 [10.  2.]]


# Support Vector Machines

In [189]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split

data = load_iris()
df = pd.DataFrame(data.data,columns=data.feature_names)
df['species'] = data.target
df

x = df.iloc[:,:4]
x

y = df.iloc[:,4:]
y

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20)

model = SVC(kernel='linear',C=1)

model.fit(x_train,y_train)

svm_pred = model.predict(x_test)

accuracy = model.score(x_test,y_test)

print('Accuracy: ',accuracy*100)

Accuracy:  96.66666666666667


C:\Users\rosha\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Building a Simple Neural Network

In [217]:
import pandas as pd
from keras import Sequential
from keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

data = load_iris()
data
df = pd.DataFrame(data.data,columns=data.feature_names)
df['species'] = data.target
df

x = df.iloc[:,:4]
x

y = df.iloc[:,4:]
y

model = Sequential()
model.add(Dense(36,input_dim=4,activation='relu'))
model.add(Dense(18,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(x,y,epochs=700,batch_size=7)

_,accuracy = model.evaluate(x,y)

print('Accuracy: ',accuracy*100)

Epoch 1/700
22/22 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.3333
Epoch 2/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.3333
Epoch 3/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.3400
Epoch 4/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4133
Epoch 5/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.5933
Epoch 6/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 7/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6533
Epoch 8/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6600
Epoch 9/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 10/700
22/22 [==============================] - 0s 2ms/step - loss:

22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 158/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 159/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 160/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 161/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 162/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 163/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 164/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 165/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 166/700
22/22 [==============================] - 0s 2ms/step - 

22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 314/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 315/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 316/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 317/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 318/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 319/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 320/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 321/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 322/700
22/22 [==============================] - 0s 1ms/step - 

22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 470/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 471/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 472/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 473/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 474/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 475/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 476/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 477/700
22/22 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 478/700
22/22 [==============================] - 0s 2ms/step - 

22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 626/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 627/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 628/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 629/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 630/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 631/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 632/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 633/700
22/22 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 634/700
22/22 [==============================] - 0s 1ms/step - 

# Importance Of Data Preprocessing in Machine Learning

In [218]:
import pandas as pd
from keras import Sequential
from keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

data = load_iris()
data
df = pd.DataFrame(data.data,columns=data.feature_names)
df['species'] = data.target
df

x = df.iloc[:,:4]
x

y = df.iloc[:,4:]
y

model = Sequential()
model.add(Dense(36,input_dim=4,activation='relu'))
model.add(Dense(18,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(x,y,epochs=200,batch_size=10)

_,accuracy = model.evaluate(x,y)

print('\nAccuracy: ',accuracy*100)

Epoch 1/200
15/15 [==============================] - 1s 2ms/step - loss: 0.0000e+00 - accuracy: 0.4667
Epoch 2/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 3/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 4/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 5/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 6/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 7/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 8/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 9/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 10/200
15/15 [==============================] - 0s 2ms/step - loss:

15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 158/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 159/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 160/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 161/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 162/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 163/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 164/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 165/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6667
Epoch 166/200
15/15 [==============================] - 0s 2ms/step - 

In [225]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Normalizer
import numpy as np

scaler = StandardScaler().fit(x)
rescaledx = scaler.transform(x)
np.set_printoptions(precision=3)
print(rescaledx[0:5,:])

print()

scaler = Normalizer().fit(x)
normalizedx = scaler.transform(x)
np.set_printoptions(precision=3)
print(normalizedx[0:5,:])

[[-0.901  1.019 -1.34  -1.315]
 [-1.143 -0.132 -1.34  -1.315]
 [-1.385  0.328 -1.397 -1.315]
 [-1.507  0.098 -1.283 -1.315]
 [-1.022  1.249 -1.34  -1.315]]

[[0.804 0.552 0.221 0.032]
 [0.828 0.507 0.237 0.034]
 [0.805 0.548 0.223 0.034]
 [0.8   0.539 0.261 0.035]
 [0.791 0.569 0.221 0.032]]


In [227]:
model = Sequential()
model.add(Dense(36,input_dim=4,activation='relu'))
model.add(Dense(18,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(rescaledx,y,epochs=200,batch_size=10)

_,accuracy = model.evaluate(rescaledx,y)

print('\nAccuracy: ',accuracy*100)

Epoch 1/200
15/15 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.2733
Epoch 2/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.5933
Epoch 3/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6200
Epoch 4/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6333
Epoch 5/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 6/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 7/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 8/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 9/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6533
Epoch 10/200
15/15 [==============================] - 0s 1ms/step - loss:

15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 158/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 159/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 160/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 161/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 162/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 163/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 164/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 165/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 166/200
15/15 [==============================] - 0s 1ms/step - 

In [228]:
model = Sequential()
model.add(Dense(36,input_dim=4,activation='relu'))
model.add(Dense(18,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(normalizedx,y,epochs=200,batch_size=10)

_,accuracy = model.evaluate(normalizedx,y)

print('\nAccuracy: ',accuracy*100)

Epoch 1/200
15/15 [==============================] - 1s 1ms/step - loss: 0.0000e+00 - accuracy: 0.3733
Epoch 2/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4200
Epoch 3/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.5400
Epoch 4/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.4600
Epoch 5/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.5733
Epoch 6/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.5267
Epoch 7/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.5800
Epoch 8/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6067
Epoch 9/200
15/15 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.6467
Epoch 10/200
15/15 [==============================] - 0s 1ms/step - loss:

15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6533
Epoch 158/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6533
Epoch 159/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6533
Epoch 160/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6533
Epoch 161/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6533
Epoch 162/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6533
Epoch 163/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6533
Epoch 164/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6533
Epoch 165/200
15/15 [==============================] - 0s 1ms/step - loss: 0.0000e+00 - accuracy: 0.6533
Epoch 166/200
15/15 [==============================] - 0s 1ms/step - 

# Linear Regression

In [255]:
import pandas as pd

# Inatializing m and c
m = 0
c = 0

X = [5.1,6.2,5.8,5.5,5.0,5.3,6.0]  # Height
Y = [54,75,67,65,54,59,69]         # Weight

# create a list of X and Y pair
print(list(zip(X,Y)))     

# create dataframe for the table of values
data = pd.DataFrame(list(zip(X,Y)),columns=['X','Y'])

print(data)

X = data['X']
X

Y = data['Y']
Y

# Learning Rate
L = 0.0001

# Number of iterations to perform gradient descent
epoches = 1000

# number of elements in X
n = float(len(X))

# Performing Gradient Descent
for i in range(epoches):
    Y_pred = m*X+c
    D_m = (-2/n)*np.sum(X*(Y-Y_pred))
    D_c = (-2/n)*np.sum(Y-Y_pred)
    m = m-L*D_m
    c = c-L*D_c
    
print(m,c)

def predict(x):
    return m*x+c

predict(6.0)

[(5.1, 54), (6.2, 75), (5.8, 67), (5.5, 65), (5.0, 54), (5.3, 59), (6.0, 69)]
     X   Y
0  5.1  54
1  6.2  75
2  5.8  67
3  5.5  65
4  5.0  54
5  5.3  59
6  6.0  69
11.054217552953162 1.9396429551719239


68.26494827289089